# Docker Compose file Reference (https://docs.docker.com/compose/compose-file/)

version: '3'

# Define services
services:

  # App Service
  app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8090:8090" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    # depends_on: 
    #   - redis # This service depends on redis. Start that first.
    # environment: # Pass environment variables to the service
    #   REDIS_URL: redis:6379    
    volumes:
      # - img-data: /app/storage
      - img-data-branches:/app/storage/branches
      - img-data-store:/app/storage/store
      - img-data-item:/app/storage/item
      - img-data-gallery:/app/storage/gallery

    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend

  # Redis Service   
  # redis:
  #   image: "redis:alpine" # Use a public Redis image to build the redis service    
  #   restart: unless-stopped
  #   networks:
  #     - backend

volumes:
  img-data-branches:
  img-data-store:
  img-data-item:
  img-data-gallery:
    driver: local
networks:
  backend:    